# Generator function to produce two-letter combinations
def two_letter_combinations(characters):
    """
    This generator function takes a list of characters as input
    and yields all possible two-letter combinations.
    """
    # Outer loop: iterates over each character as the first letter
    for char1 in characters:
        # Inner loop: iterates over each character as the second letter
        for char2 in characters:
            # Yield a two-letter combination
            yield char1 + char2

# Main method to call the generator function and print combinations
def main():
    """
    The main function that demonstrates the usage of the generator.
    It creates a list of characters and prints all two-letter combinations
    generated by the two_letter_combinations function.
    """
    # Original list of 5 characters
    characters = ['p', 'q', 'r', 's', 't']
    
    # Print each combination produced by the generator
    print("All possible two-letter combinations:")
    for combination in two_letter_combinations(characters):
        print(combination)

# Call the main function
main()